### ISSUE TITLE
Design nepalihackers.github.io page.

### ISSUE THREAD

**Issue by swornim00** [nepalihackers/ideas#2]
Let's design the page first and we should work on other projects. I think designing the page is the first thing we need to do.

**Comment by techgaun** [comment]
@bravegurkha good point.. are you willing to volunteer? Or have suggestions on particular stuff that can bootstrap the pages.. I'm not much inito designing but I could try too.

**Comment by swornim00** [comment]
I will do it. As soon as my exams are over. We can use templates.

**Comment by gitnepal** [comment]
:heart:

**Comment by techgaun** [comment]
the initial work has been done by @swornimshrestha. now we can add issues on the site repo itself for enhancements on top of it.
